# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: mconfig.proto for package 'mconfig'

require 'grpc'
require 'mconfig_pb'

module Mconfig
  module Config
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'mconfig.Config'

      rpc :Create, ::Mconfig::ConfigCreateRequest, ::Mconfig::ConfigCreateResponse
    end

    Stub = Service.rpc_stub_class
  end
end
